"""empty message

Revision ID: 31cc014da672
Revises: None
Create Date: 2019-09-25 23:58:04.777913

"""

# revision identifiers, used by Alembic.
revision = '31cc014da672'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dnsqueue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_name', sa.String(), nullable=True),
    sa.Column('domain_class', sa.String(), nullable=True),
    sa.Column('domain_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tcppacket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('destination_ip', sa.String(), nullable=True),
    sa.Column('source_port', sa.Integer(), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tcppacket')
    op.drop_table('dnsqueue')
    # ### end Alembic commands ###
